version: "2"

services:
  docker-test:
    container_name: docker-test
    restart: always
    build: .
    ports:
      - "3000:80"
    links:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"